---
title: "NHL_JSON"
author: "Zack Vaskalis"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library packages needed:    

`library(tidyverse)`    
`library(pipeR)`    
`library(DT)`    
`library(knitr)`    
`library(dplyr)`    
`library(jsonlite)`    
`library(httr)`    
`library(ggplot2)`    
`library(DBI)`     

```{r LoadLibraries, include=FALSE, message=FALSE, echo=TRUE, results='hide'}
library(tidyverse)
library(pipeR)
library(DT)
library(knitr)
library(dplyr)
library(jsonlite)
library(httr)
library(ggplot2)
library(DBI)
```

```{r franchise, echo=TRUE}
#Function to get Franchises
  getFranchises <- function(...)
  {
#franchise json data.  Set up components of URL for API query using GET() function
    query_prefix <- 'https://records.nhl.com/site/api'
    query_suffix <- '/franchise'
    franchiseJSON <- GET(paste0(query_prefix,query_suffix))

#Transform Data from JSON to a data frame
    franchiseData <- fromJSON(content(franchiseJSON,"text", encoding = "UTF-8"),flatten = TRUE) 

#Rename id to franchiseID
    franchiseData <- rename(franchiseData$data, franchiseId = id)
    franchiseData

#Reorganize the data frame with columns in a more usable order
    franchiseData %>% select(mostRecentTeamId, franchiseId, teamPlaceName, teamCommonName,
                             firstSeasonId, lastSeasonId) %>%
      arrange(teamPlaceName) %>>% (~ franchiseData)
    franchiseDT <- datatable(franchiseData, rownames = FALSE)

#Initialize franchiseSelection Table for user to be able to see correct franchise ID for functions #3 - 5.
    franchiseSelection <- franchiseData

#return Data
    return(franchiseSelection)
  }
```

```{r callgetFranchise, echo=TRUE}
  datatable(getFranchises())
```

```{r franchiseTotals, echo=TRUE}
#function to get Franchise Totals
  getFranchiseTotals <- function(...)
  {
#franchise team totals json data.  Set up components of URL for API query using GET() function
    query_prefix <- 'https://records.nhl.com/site/api'
    query_suffix <- '/franchise-team-totals'

#Get JSON Data
    franchiseTeamTotsJSON <- GET(paste0(query_prefix,query_suffix))
    franchiseTeamTotsData <- fromJSON(content(franchiseTeamTotsJSON,"text", encoding = "UTF-8"),flatten = TRUE)

#Reorganize the data frame with columns in a more usable order
    franchiseTeamTotsDataTBL <- tibble::as_tibble(franchiseTeamTotsData)
    franchiseTeamTotsDataTBL$data %>%
      select(franchiseId, teamName, triCode, wins, losses, ties, overtimeLosses, shutouts, shootoutWins,
             shootoutLosses, penaltyMinutes, points, pointPctg, homeWins, homeLosses, homeTies,
             homeOvertimeLosses, roadWins, roadLosses, roadTies, roadOvertimeLosses, gameTypeId,
             gamesPlayed, goalsAgainst, goalsFor, id, teamId, activeFranchise, firstSeasonId, lastSeasonId) %>%
      arrange(teamName) %>>% (~ franchiseTeamTotsDataTBL)

#return Data
    return(franchiseTeamTotsDataTBL)
  }
```

```{r callgetFranchiseTotals, echo=TRUE}
  franchiseFull <- getFranchiseTotals()
  datatable(franchiseFull[c(1:8)])
```

```{r listOfFranchises, echo=TRUE}
  franchiseSelection <- getFranchises()
  franchiseSelection %>% select(franchiseId, teamPlaceName, teamCommonName) %>% arrange(teamPlaceName) %>>%
    (~ frSelect) %>% datatable(frSelect,rownames = FALSE)
```

```{r franchiseSpecificTotals, echo=TRUE}
#Function to get Franchise Specific Totals
  getFranchiseSpecificTotals <- function(FranID, ...)
  {
#Specific franchise team totals json data
    query_prefix <- 'https://records.nhl.com/site/api'
    query_suffix <- '/franchise-season-records?cayenneExp=franchiseId='

#Get Specific Team Input from User
    specific_franchiseID <- FranID

#Get JSON Data
    franchiseIDTeamTotsDataJSON <- GET(paste0(query_prefix,query_suffix,specific_franchiseID))
    franchiseIDTeamTotsData <- fromJSON(content(franchiseIDTeamTotsDataJSON,"text", encoding = "UTF-8"),
                                        flatten = TRUE)

#Reorganize the data frame with columns in a more usable order
    franchiseIDTeamTotsDataTBL <- tibble::as_tibble(franchiseIDTeamTotsData)
    franchiseIDTeamTotsDataTBL$data %>% select(franchiseName, franchiseId, id:winlessStreakDates) %>>%
      (~ franchiseIDTeamTotsDataTBL)

#Return Data    
    return(franchiseIDTeamTotsDataTBL)
  }
```

```{r callgetFranchiseSpecificTotals, echo=TRUE}
#Two test function calls - one for my favorite team, GO PENS! & one for the hometown favorite Hurricanes!
#function to pull records for Pittsburgh Penguins

  datatable(t(getFranchiseSpecificTotals(17)), colnames = "")

#Function to pull records for Carolina Hurricanes

  datatable(t(getFranchiseSpecificTotals(26)), colnames = "")
```

```{r franchiseGoalieRecords, echo=TRUE}
#Function to get Franchise Goalie Records
  getFranchiseGoalieRecords <- function(FranID, ...)
  {
#Specific franchise Goalie Records json data
    query_prefix <- 'https://records.nhl.com/site/api'
    query_suffix <- '/franchise-goalie-records?cayenneExp=franchiseId='

#Get Specific Team Input from User
    specific_franchiseID <- FranID

#Get JSON Data
    franchiseIDGoalieJSON <- GET(paste0(query_prefix,query_suffix,specific_franchiseID))
    franchiseIDGoalieData <- fromJSON(content(franchiseIDGoalieJSON,"text", encoding = "UTF-8"),
                                      flatten = TRUE)

#Reorganize the data frame with columns in a more usable order

    goalieDF <- franchiseIDGoalieData$data
    goalieDF %>% select(franchiseId, franchiseName, firstName, lastName, gamesPlayed, wins,
                        losses, ties, mostSavesOneGame, mostShotsAgainstOneGame,
                        mostGoalsAgainstOneGame, id:wins) %>>% (~ goalieDF)

#Return data
    return(goalieDF)
  }
```

```{r callgetFranchiseGoalieRecords, echo=TRUE}
#Two test function calls - one for my favorite team, GO PENS! & one for the hometown favorite Hurricanes!
#function to pull records for Pittsburgh Penguins and print out first 8 columns to display well on the page

  goalieFull <- getFranchiseGoalieRecords(17)
  datatable(goalieFull[c(1:8)])

#Function to pull records for Carolina Hurricanes and print out first 8 columns to display well on the page

  goalieFull <- getFranchiseGoalieRecords(26)
  datatable(goalieFull[c(1:8)])
```

```{r franchiseSkaterRecords, echo=TRUE}
#Function to get Franchise Skater Records
  getFranchiseSkaterRecords <- function(FranID, ...)
  {

#Specific franchise Skater Records json data
    query_prefix <- 'https://records.nhl.com/site/api'
    query_suffix <- '/franchise-skater-records?cayenneExp=franchiseId='

#Get Specific Team Input from User
    specific_franchiseID <- FranID
    
#Get JSON Data
    franchiseIDSkaterJSON <- GET(paste0(query_prefix,query_suffix,specific_franchiseID))
    franchiseIDSkaterData <- fromJSON(content(franchiseIDSkaterJSON,"text", encoding = "UTF-8"),
                                      flatten = TRUE)

#Reorganize the data frame with columns in a more usable order

    skaterDF <- franchiseIDSkaterData$data
    skaterDF %>% select(franchiseId, franchiseName, firstName, lastName, positionCode, 
                        gamesPlayed, goals, assists, penaltyMinutes, mostGoalsOneGame, mostAssistsOneGame,
                        mostPenaltyMinutesOneSeason, id:seasons) %>% arrange(desc(goals)) %>>% (~ skaterDF)
    
#Return Data
    return(skaterDF)
  }
```

```{r callgetFranchiseSkaterRecords, echo=TRUE}
#Two test function calls - one for my favorite team, GO PENS! & one for the hometown favorite Hurricanes!
#function to pull records for Pittsburgh Penguins. Variable teamFull has full dataset. Needed to subset to display
  skaterFull <- getFranchiseSkaterRecords(17)
  datatable(skaterFull[c(1:8)])

#Function to pull records for Carolina Hurricanes and print out first 8 columns to display well on the page

  skaterFull <- getFranchiseSkaterRecords(26)
  datatable(skaterFull[c(1:8)])
```

```{r EDA_Plots, echo=TRUE}

#Get FULL Pittsburgh Goalie and Skater Datasets
  goalieFull <- getFranchiseGoalieRecords(17)
  #datatable(goalieFull)

  skaterFull <- getFranchiseSkaterRecords(17)
  #datatable(skaterFull)
  
#Penguins Official Colors from: https://teamcolorcodes.com/pittsburgh-penguins-color-codes/
  pensColors <- c("#000000", "#CFC493", "#FCB514", "#FFFFFF")
  pensColors2 <- c("#000000", "#000000", "#000000", "#000000", "#CFC493", "#CFC493",
                   "#CFC493", "#CFC493")

#All time Pens Skaters by Position
  g1 <- ggplot(data=skaterFull, aes(x = positionCode))
  g1 + geom_bar() + labs(x = "Penguins Skater Position",
                        title = "Pittsburgh Penguins All Time Skater Positions") +
    scale_x_discrete(labels = c("Center", "Defense", "Left Wing", "Right Wing")) +
    coord_flip()
  
#All time Pens Skaters by Position and Active = Yes/No Status
  g2 <- ggplot(data=skaterFull, aes(x = positionCode, group = activePlayer))
  g2 + geom_bar(fill=pensColors2, position = "dodge") +
    labs(x = "Penguins Skater Position", title = "Pittsburgh Penguins All Time Skater Positions") +
    scale_x_discrete(labels = c("Center", "Defense", "Left Wing", "Right Wing")) +
    scale_fill_discrete(name = "Active Player?", labels = c("FALSE" = "No", "TRUE" = "Yes"))
  
#All time Pens Skater Most Points in One Game by Position
  g3 <- ggplot(skaterFull, aes(x = positionCode, y = mostPointsOneGame))
  g3 + geom_boxplot(fill=pensColors[3]) +
    labs(x = "Penguins Skater Position",
         title = "Pittsburgh Penguins Most Points in One Game by Position") +
    scale_x_discrete(labels = c("Center", "Defense", "Left Wing", "Right Wing"))
  
#All time Pens Skater Scatterplot of Goals vs Penalty Minutes
  ggplot()+
  geom_point(data = skaterFull, aes(x = goals, y = penaltyMinutes, color = positionCode),size=4) +
      scale_color_manual(values = pensColors) +
    labs(x = "Total Goals", title = "Pittsburgh Penguins Goals by Penalty Minutes Colored by Position")
    
#New Variable OffDef: Take positionCOde and Transform: C, L, R = Offense, D = Defense
  skaterFull <- mutate(skaterFull, OffDef = ifelse((positionCode == "D"), "Defense", "Offense"))
      
#Run Same plot again, now with new variable
  ggplot()+
  geom_point(data = skaterFull, aes(x = goals, y = penaltyMinutes, color = OffDef),size=4) +
      scale_color_manual(values = pensColors) +
    labs(x = "Total Goals", title = "Pittsburgh Penguins Goals by Penalty Minutes Colored by Position")
  
  
```

```{r EDA_Tables, echo=TRUE}

#Get FULL Pittsburgh Goalie and Skater Datasets
  goalieFull <- getFranchiseGoalieRecords(17)
  #datatable(goalieFull)

  skaterFull <- getFranchiseSkaterRecords(17)
  #datatable(skaterFull)

#New Variable OffDef: Take positionCOde and Transform: C, L, R = Offense, D = Defense
  skaterFull <- mutate(skaterFull, OffDef = ifelse((positionCode == "D"), "Defense", "Offense"))  

#Numerical Summary of means and standard deviations for points, assists, goals, and penalty minutes
  skaterFull %>% group_by(OffDef) %>% summarize(avg_points = mean(points), sd_points = sd(points),
                                                avg_assists = mean(assists), sd_assists = sd(assists),
                                                avg_goals = mean(goals), sd_goals = sd(goals),
                                                avg_penaltyMin = mean(penaltyMinutes),
                                                sd_penaltyMin = sd(penaltyMinutes))
  
#Numerical Summary Statistics for Penguins Skaters
  summaryTBL <- tibble(summary(skaterFull$points, digits = 4), summary(skaterFull$goals, digits = 4),
                       summary(skaterFull$assists, digits = 4), summary(skaterFull$penaltyMinutes, digits = 4))
  summaryTBL <- rename(summaryTBL, "points" = "summary(skaterFull$points, digits = 4)",
                       "goals" = "summary(skaterFull$goals, digits = 4)" ,
                       "assists" = "summary(skaterFull$assists, digits = 4)",
                       "Penalty Minutes" = "summary(skaterFull$penaltyMinutes, digits = 4)")
  attr(summaryTBL, "row.names") <- c("Min.", "1st Qu.", "Median", "Mean", "3rd Qu.", "Max.")
  datatable(summaryTBL)
  
#Three way contingency table to show most points in one game by position code
#Tables are separated by active (TRUE) and non-active (FALSE) players
  table(skaterFull$positionCode,skaterFull$mostPointsOneGame,skaterFull$activePlayer)
  
#Another Three way contingency table using created variable OffDef show most points in one game
#by Offense vs Defense.  Tables are again separated by active (TRUE) and non-active (FALSE) players
  table(skaterFull$OffDef,skaterFull$mostPointsOneGame,skaterFull$activePlayer)
  
```


